### ISSUE TITLE
[FEATURE]: Support for Older Python Versions (<3.9)

### ISSUE THREAD

**Issue by eneserdo** [epistoteles/TensorHue#9]
Can you please make it compatible with python <3.9? I changed the required parts in the setup.cfg etc. to make it installable in python 3.8 and installed it from setup.py, and it works as far as I can tell. (Though I had to change type hints `list` -> `List`, `tuple` -> `Tuple` etc.). 

I would have created a pull request but I could not run the tests (due to jax being a headache to install in my machine)

Thanks in advance!

**Comment by epistoteles** [comment]
Hi @eneserdo!

Feel free to create a pull request nonetheless - the tests should run automatically trough GitHub Actions, without the need to set up anything locally. If they don't pass, I can contribute your pull request.

Ideally your PR is based on the most current version (0.0.16).

Let me know if you have any questions or I can help :) would be great to have you onboard as the first contributor!

**Comment by epistoteles** [comment]
Hey @eneserdo :)

I merged your PR and (with one minor modification) released a new TensorHue version 0.0.17 that now supports Python>=3.7.

Thank you for being the first contributor to TensorHue! 🎉
